package com.jesus.testapp.util;

import java.util.ArrayList;
import java.util.List;

public class Constants {

    private Constants(){}

    public static final List<String> nmFields = List.of("Tipo de mensaje", "País", "Host origen", "Id único de la transacción", "Canal", "Identificador del cliente", "Perfil", "Segmento", "Online Flag", "Flag que indica si se requiere respuesta de Lynx.", "Modo de acceso (Subcanal)", "SESSION_ID", "Username", "IP", "UserAgent", "Locale", "Fecha y Hora Sesión", "Medio de autentificación", "Tipo de transacción", "Fecha y hora", "Código de respuesta", "Pregunta desafío", "Id de sucursal/ Número de teléfono", "Tarjeta", "Tipo de cuenta", "Cuenta", "Número de Celular", "E-mail", "Timestamp de Salida", "Device", "Modelo", "Idiomas", "Geolocalización", "isBot", "isDataCurrupted", "isSessionCorrupted", "isWhitelisted", "scoreBiometrico", "recognitionRatioBiometrico", "confidenceBiometrico", "Uso Futuro", "Delimitador del mensaje");
    public static final List<String> pbFields = List.of("Tipo de mensaje", "País", "Host origen", "Id único de la transacción", "Canal", "Identificador de cliente", "Perfil", "Segmento", "Online Flag", "Flag de repuesta requerida de Lynx", "Modo de acceso", "SESSION_ID", "Username", "IP", "UserAgent", "Locale", "Fecha y Hora Sesión", "Medio de Autentificación", "Tipo de transacción", "Tipo de firma", "Número de móvil/Código Proceso", "Tipo de cuenta principal/cliente", "Cuenta principal/cliente", "Entidad principal/cliente", "País principal/cliente", "Oficina de la cuenta principal/cliente", "Cuenta Destino", "Entidad Destino", "País Destino", "Oficina de la cuenta Destino", "Nombre del beneficiario/ordenante", "Fecha y hora del pago", "Comentario/Código Leyenda", "Importe de la transacción", "Importe en moneda original", "Moneda original", "Folio SPEI", "Email del beneficiario para notificación", "Flag Asíncrono", "Tarjeta de carga/descarga de efectivo", "Número móvil recargado", "Operadora del móvil recargado", "País del móvil recargado", "Tipo de Tarjeta", "ID del pago recurrente o diferido", "timing de la transferencia/traspaso programado", "Periodicidad del pago programado", "Día de la semana/mes", "Flag indicador de primer pago de un pago recurrente", "Fecha de ejecución del primer pago asociado a este pago recurrente", "Importe inicial con el que se configuró el pago recurrente", "Importe actual con el que está configurado el pago recurrente", "Fecha de planificación del pago", "Código de respuesta", "Saldo de la cuenta principal/cliente", "No-Monetaria / Crédito / Débito Flag", "Sucursal ID/ Número de teléfono", "IBAN cuenta Cliente", "IBAN cuenta Destino", "Tarjeta de destino", "Nº de contrato CIE", "Timestamp de Salida", "Referencia Pago CIE", "Nombre del pago CIE", "Concepto Pago CIE", "Identificador OP frecuente", "Fecha Alta OP frecuente", "Fecha Alta del Canal", "Fecha de (re)activación del canal", "Usuario que realiza alta en el canal", "Fecha de nacimiento Titular Cuenta Principal/Cliente", "Fecha de Alta de la Cuenta Principal/Cliente", "Número Último Movimiento Cuenta Principal/Cliente", "Fecha Último Movimiento Cuenta Principal/Cliente", "Sector de la Cuenta Principal/Cliente", "Segmento de la Cuenta Principal/Cliente", "Fecha de nacimiento Titular Cuenta secundaria/asociada", "Fecha de Alta de la Cuenta secundaria/asociada", "Número Último Movimiento Cuenta secundaria/asociada", "Fecha Último Movimiento Cuenta secundaria/asociada", "Sector de la Cuenta secundaria/asociada", "Segmento de la Cuenta secundaria/asociada", "CR Oficina Gestora Cuenta principal/cliente", "CR Oficina Gestora Cuenta secundaria/asociada", "ID cliente secundario/asociado", "Uso Futuro", "Delimitador del mensaje");
    public static final List<String> opFields = List.of("Tipo de mensaje",
            "Host origen",
            "ID único",
            "Código de mensaje",
            "Número de tarjeta o PAN",
            "Tipo de tarjeta",
            "Código de proceso",
            "Importe de la transacción",
            "Fecha y hora de la operación",
            "Fecha y hora original",
            "Fecha de expiración",
            "MCC",
            "País origen del comercio",
            "POS Condition Code",
            "Entry Mode",
            "ECI/VBV",
            "Service code",
            "Indicador de CVV2",
            "Validación CVV2",
            "Indicador de capacidad para transferir datos de la tarjeta a la terminal",
            "Posición 3 Capacidad de aceptación del NIP",
            "Indicador de capacidad de captura de Tarjetas",
            "Indica si la terminal es atendida por el comercio",
            "Indicador de presencia del tarjetahabiente",
            "Indicador de presencia de la tarjeta",
            "ID del adquirente",
            "ID de la red",
            "ID de autorizador",
            "Código de Respuesta",
            "ID del Comercio",
            "ID Terminal",
            "Nombre del comercio",
            "Nombre de la ciudad del comercio",
            "Número de TeléfonoMóvil",
            "Indicador de operación online",
            "Importe en moneda original",
            "Código de la moneda original",
            "TVR",
            "CVR",
            "ID único de la operación original",
            "Código de razón",
            "Indicador de Fallback",
            "CV3",
            "Motivo de la respuesta en comunicaciones de denegación",
            "Caducidad errónea en comunicación de denegación por control o alerta",
            "ID del emisor",
            "Modo de autenticación especial",
            "Score de Visa",
            "Token Q2",
            "EMV",
            "NIP_OFFLINE",
            "AIP",
            "ATC",
            "Grupo",
            "Cadena",
            "ARQC",
            "Código Postal",
            "Dispositivo Biométrico",
            "Cliente Biométrico",
            "Resultado Biométrico",
            "Cliente ID",
            "Fecha activación canal",
            "UsoFuturo",
            "Timestamp");
}
